CREATE TABLE tasks (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       title VARCHAR(100) NOT NULL,
                       description TEXT,
                       status VARCHAR(20) NOT NULL,
                       created_at TIMESTAMP NOT NULL,
                       updated_at TIMESTAMP NOT NULL
);